### ISSUE TITLE
why to use this dependency in master

### ISSUE THREAD

**Issue by Jaswanth-S** [sankeerthana1762/SpringBootTask#6]
<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<version>2.3.4</version>
		</dependency>

**Comment by Jaswanth-S** [comment]
<dependency>
			<groupId>org.javassist</groupId>
			<artifactId>javassist</artifactId>
			<version>3.25.0-GA</version>
		</dependency>

**Comment by Jaswanth-S** [comment]
<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-orm</artifactId>
			<version>5.1.8.RELEASE</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-tx</artifactId>
			<version>5.1.8.RELEASE</version>
		</dependency>

**Comment by sankeerthana1762** [comment]
issue closed

**Comment by sankeerthana1762** [comment]
issue closed
