### ISSUE TITLE
why to use both of these dependencies in master pom

### ISSUE THREAD

**Issue by Jaswanth-S** [sankeerthana1762/SpringBootTask#7]
<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>1.4.193</version>
		</dependency>

**Comment by sankeerthana1762** [comment]
issue closed
